name: Manual Publish
run-name: Deploy ${{ github.event.inputs.version }} to ${{ github.event.inputs.target }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      target:
        description: "选择发版目标"
        required: true
        default: "backend"
        type: choice
        options:
          - backend
      version:
        description: "版本号 (如 v1.0.0)"
        required: true

jobs:
  # --- 后端构建任务 ---
  build-backend:
    if: ${{ github.event.inputs.target == 'backend'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 登录 GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 打包 & 推送后端镜像
        uses: docker/build-push-action@v5
        with:
          context: . # 这里的路径必须对应你的子目录
          push: true
          tags: |
            ghcr.io/dancingcodes/pic-backend:${{ github.event.inputs.version }}
            ghcr.io/dancingcodes/pic-backend:latest

      - name: 远程部署
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/pic
            docker compose pull backend
            docker compose up -d backend